In [22]:
import pandas as pd
import os
from datetime import datetime


pasta_2021 = 'C:\\Users\\enzo.pedrica\\Desktop\\Dados Financeiros\\01 - Bronze\\2021'
pasta_2022 = 'C:\\Users\\enzo.pedrica\\Desktop\\Dados Financeiros\\01 - Bronze\\2022'
pasta_2023 = 'C:\\Users\\enzo.pedrica\\Desktop\\Dados Financeiros\\01 - Bronze\\2023'
pasta_2024 = 'C:\\Users\\enzo.pedrica\\Desktop\\Dados Financeiros\\01 - Bronze\\2024'

# Dicionário com nomes personalizados para os arquivos
arquivos_2021 = {
    'janeiro_21': '2021-01.csv',
    'fevereiro_21': '2021-02.csv',
    'marco_21': '2021-03.csv',
    'abril_21': '2021-04.csv',
    'maio_21': '2021-05.csv',
    'junho_21': '2021-06.csv',
    'julho_21': '2021-07.csv',
    'agosto_21': '2021-08.csv',
    'setembro_21': '2021-09.csv',
    'outubro_21': '2021-10.csv',
    'novembro_21': '2021-11.csv',
    'dezembro_21': '2021-12.csv'
}
arquivos_2022 = {
    'janeiro_22': '2022-01.csv',
    'fevereiro_22': '2022-02.csv',
    'marco_22': '2022-03.csv',
    'abril_22': '2022-04.csv',
    'maio_22': '2022-05.csv',
    'junho_22': '2022-06.csv',
    'julho_22': '2022-07.csv',
    'agosto_22': '2022-08.csv',
    'setembro_22': '2022-09.csv',
    'outubro_22': '2022-10.csv',
    'novembro_22': '2022-11.csv',
    'dezembro_22': '2022-12.csv'
}
arquivos_2023 = {
    'janeiro_23': '2023-01.csv',
    'fevereiro_23': '2023-02.csv',
    'marco_23': '2023-03.csv',
    'abril_23': '2023-04.csv',
    'maio_23': '2023-05.csv',
    'junho_23': '2023-06.csv',
    'julho_23': '2023-07.csv',
    'agosto_23': '2023-08.csv',
    'setembro_23': '2023-09.csv',
    'outubro_23': '2023-10.csv',
    'novembro_23': '2023-11.csv',
    'dezembro_23': '2023-12.csv'
}
arquivos_2024 = {
    'janeiro_24': '2024-01.csv',
    'fevereiro_24': '2024-02.csv',
    'marco_24': '2024-03.csv',
    'abril_24': '2024-04.csv',
    'maio_24': '2024-05.csv',
    'junho_24': '2024-06.csv',
    'julho_24': '2024-07.csv',
    'agosto_24': '2024-08.csv',
    'setembro_24': '2024-09.csv',
    'outubro_24': '2024-10.csv',
    'novembro_24': '2024-11.csv',
    'dezembro_24': '2024-12.csv'
}
dfs_21 = []
dfs_22 = []
dfs_23 = []
dfs_24 = []


for nome, arquivo in arquivos_2021.items():
    caminho_completo = os.path.join(pasta_2021, arquivo)
    df_21 = pd.read_csv(caminho_completo)
    df_21['arquivo_origem'] = nome
    dfs_21.append(df_21)

for nome, arquivo in arquivos_2022.items():
    caminho_completo = os.path.join(pasta_2022, arquivo)
    df_22 = pd.read_csv(caminho_completo)
    df_22['arquivo_origem'] = nome
    dfs_22.append(df_22)

for nome, arquivo in arquivos_2023.items():
    caminho_completo = os.path.join(pasta_2023, arquivo)
    df_23 = pd.read_csv(caminho_completo)
    df_23['arquivo_origem'] = nome
    dfs_23.append(df_23)

for nome, arquivo in arquivos_2024.items():
    caminho_completo = os.path.join(pasta_2024, arquivo)
    df_24 = pd.read_csv(caminho_completo)
    df_24['arquivo_origem'] = nome
    dfs_24.append(df_24)

# Concatenar todos os DataFrames em um único
df_21 = pd.concat(dfs_21, ignore_index=True)
df_22 = pd.concat(dfs_22, ignore_index=True)
df_23 = pd.concat(dfs_23, ignore_index=True)
df_24 = pd.concat(dfs_24, ignore_index=True)

In [23]:
# Remove duplicatas
df_21.drop_duplicates(inplace=True)
df_21['timestamp'] = pd.to_datetime(df_21['timestamp'])
df_21['year'] = df_21['timestamp'].dt.year
df_21['month'] = df_21['timestamp'].dt.month
df_21['day'] = df_21['timestamp'].dt.day
df_21['time'] = df_21['timestamp'].dt.time
df_21.head()

,timestamp,open,high,low,close,volume,arquivo_origem,{,year,month,day,time
0,2025-07-03 17:00:00,291.97,291.9700,291.97,291.97,309839.0,janeiro_21,NaN,2025.0,7.0,3.0,17:00:00
1,2025-07-03 16:55:00,291.52,291.9500,291.51,291.51,65.0,janeiro_21,NaN,2025.0,7.0,3.0,16:55:00
2,2025-07-03 16:50:00,291.51,291.5900,291.51,291.52,115.0,janeiro_21,NaN,2025.0,7.0,3.0,16:50:00
3,2025-07-03 16:45:00,291.69,291.7673,291.51,291.51,646.0,janeiro_21,NaN,2025.0,7.0,3.0,16:45:00
4,2025-07-03 16:40:00,291.64,291.6900,291.64,291.69,93.0,janeiro_21,NaN,2025.0,7.0,3.0,16:40:00

In [24]:
# Remove duplicatas
df_22.drop_duplicates(inplace=True)
df_22['timestamp'] = pd.to_datetime(df_22['timestamp'])
df_22['year'] = df_22['timestamp'].dt.year
df_22['month'] = df_22['timestamp'].dt.month
df_22['day'] = df_22['timestamp'].dt.day
df_22['time'] = df_22['timestamp'].dt.time
df_22.head()

KeyError: 'timestamp'

In [ ]:
# Remove duplicatas
df_23.drop_duplicates(inplace=True)
df_23['timestamp'] = pd.to_datetime(df_23['timestamp'])
df_23['year'] = df_23['timestamp'].dt.year
df_23['month'] = df_23['timestamp'].dt.month
df_23['day'] = df_23['timestamp'].dt.day
df_23['time'] = df_23['timestamp'].dt.time
df_23.head()

In [ ]:
# Remove duplicatas
df_24.drop_duplicates(inplace=True)
df_24['timestamp'] = pd.to_datetime(df_24['timestamp'])
df_24['year'] = df_24['timestamp'].dt.year
df_24['month'] = df_24['timestamp'].dt.month
df_24['day'] = df_24['timestamp'].dt.day
df_24['time'] = df_24['timestamp'].dt.time
df_24.head()